import Head from "next/head";
import Footer from "../comps/footer";
import NavBar from "../comps/navbar";
import Link from "next/link";
import TwitterIcon from '@mui/icons-material/Twitter';
import InstagramIcon from '@mui/icons-material/Instagram';
import GitHubIcon from '@mui/icons-material/GitHub';
import LinkedInIcon from '@mui/icons-material/LinkedIn';
import EmailIcon from '@mui/icons-material/Email';
import Image from "next/image";


const About = () => {
    return (<>
        <Head>
            <title>About</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar />
        <div className="px-16 py-5 mb-16 grid grid-cols-2 gap-5">
            <div className=" mt-6 space-y-7 text-base text-zinc-400">
                <h1 className='text-4xl font-bold text-zinc-100 '>I’m Spencer Sharp. I live in New York City, where I design the future.</h1>
                <p> I’ve loved making things for as long as I can remember, and wrote my first program when I was 6 years old, just two weeks after my mom brought home the brand new Macintosh LC 550 that I taught myself to type on.</p>
                <p>The only thing I loved more than computers as a kid was space. When I was 8, I climbed the 40-foot oak tree at the back of our yard while wearing my older sister’s motorcycle helmet, counted down from three, and jumped — hoping the tree was tall enough that with just a bit of momentum I’d be able to get to orbit.</p>
                <p> I spent the next few summers indoors working on a rocket design, while I recovered from the multiple surgeries it took to fix my badly broken legs. It took nine iterations, but when I was 15 I sent my dad’s Blackberry into orbit and was able to transmit a photo back down to our family computer from space.</p>
                <p> Today, I’m the founder of Planetaria, where we’re working on civilian space suits and manned shuttle kits you can assemble at home so that the next generation of kids really can make it to orbit — from the comfort of their own backyards.</p>
            </div>
            <div className='ml-10'>
                <Image className=' w-96 mb-16 rounded-xl rotate-2'
                    src='/portrait.webp'
                    alt='portrait'
                    height='640'
                    width='640'
                />
                <div className="border-b-2 border-zinc-400 pb-16">
                    <Link href='https://www.twitter.com/'>
                        <p className="flex mt-4 text-sm font-medium text-zinc-200 hover:text-teal-500">
                            <TwitterIcon />
                            <span className='ml-4'>Follow on Twitter</span>
                        </p>
                    </Link>
                    <Link href='https://www.instagram.com/'>
                        <p className="flex  mt-4  text-sm font-medium text-zinc-200 hover:text-teal-500">
                            <InstagramIcon />
                            <span className='ml-4'>Follow on Instagram</span>
                        </p>
                    </Link>
                    <Link href='https://www.github.com/'>
                        <p className="flex  mt-4 text-sm font-medium text-zinc-200 hover:text-teal-500">
                            <GitHubIcon />
                            <span className='ml-4'>Follow on GitHub</span>
                        </p>
                    </Link>
                    <Link href='https://www.linkedin.com/'>
                        <p className="flex  mt-4 text-sm font-medium text-zinc-200 hover:text-teal-500">
                            <LinkedInIcon />
                            <span className='ml-4'>Follow on LinkedIn</span>
                        </p>
                    </Link>
                </div>
                <div>
                    <Link href='mailto:spencer@planetaria.tech'>
                        <p className="flex  mt-4 text-sm font-medium text-zinc-200 hover:text-teal-500">
                            <EmailIcon />
                            <span className='ml-4'>spencer@planetaria.tech</span>
                        </p>
                    </Link>
                </div>
            </div>
        </div>
        <Footer />
    </>
    )
}
export default About;