import Head from "next/head";
import Image from "next/image";
import Navbar from "../comps/navbar";
import Footer from "../comps/footer";
import TwitterIcon from "@mui/icons-material/Twitter";
import InstagramIcon from "@mui/icons-material/Instagram";
import GitHubIcon from "@mui/icons-material/GitHub";
import LinkedInIcon from "@mui/icons-material/LinkedIn";
import MailOutlineIcon from "@mui/icons-material/MailOutline";
import BusinessCenterIcon from "@mui/icons-material/BusinessCenter";
import ArrowDownwardIcon from "@mui/icons-material/ArrowDownward";
import Link from "next/link";
import { URLS } from "../constants/urls";
import { type Key } from "react";
import { api } from "y/utils/api";

export default function Home() {
  const articles = api.articles.getAll.useQuery();
  const data = articles.data;
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <div className="w-3/4 px-16 py-5">
          <h1 className="text-4xl font-bold tracking-tight text-zinc-100 ">
            Software designer, founder, and amateur astronaut.
          </h1>
          <p className="mt-6 text-base text-zinc-400">
            I’m Spencer, a software designer and entrepreneur based in New York
            City. I’m the founder and CEO of Planetaria, where we develop
            technologies that empower regular people to explore space on their
            own terms.
          </p>
        </div>
        <div className="px-16 pb-16">
          <Link href="https://www.twitter.com/">
            <TwitterIcon className="mr-4 text-zinc-400" />
          </Link>
          <Link href="https://www.instagram.com/">
            <InstagramIcon className="mr-4 text-zinc-400" />
          </Link>
          <Link href="https://www.github.com/">
            <GitHubIcon className="mr-4 text-zinc-400" />
          </Link>
          <Link href="https://www.linkedin.com">
            <LinkedInIcon className="mr-4 text-zinc-400" />
          </Link>
        </div>
        <div className="abso -my-4 flex justify-center gap-5 py-4 pb-16">
          <Image
            className="relative aspect-[9/10] w-72 flex-none rotate-2 overflow-hidden rounded-xl object-cover"
            src="/image-1.webp"
            alt=""
            height="384"
            width="576"
          />
          <Image
            className="relative aspect-[9/10] w-72 flex-none -rotate-2 overflow-hidden rounded-xl object-cover"
            src="/image-2.webp"
            alt=""
            height="256"
            width="384"
          />
          <Image
            className="relative aspect-[9/10] w-72 flex-none rotate-2 overflow-hidden rounded-xl object-cover"
            src="/image-3.webp"
            alt=""
            height="256"
            width="384"
          />
          <Image
            className="relative aspect-[9/10] w-72 flex-none -rotate-2 overflow-hidden rounded-xl object-cover"
            src="/image-4.webp"
            alt=""
            height="480"
            width="384"
          />
          <Image
            className="relative aspect-[9/10] w-72 flex-none rotate-2 overflow-hidden rounded-xl object-cover"
            src="/image-5.webp"
            alt=""
            height="216"
            width="384"
          />
        </div>
        <div className="grid grid-cols-2">
          <div className="gap-5 pl-16">
            {data?.map(
              (article: {
                id: Key;
                createdAt: Object;
                title: string;
                content: string;
              }) => (
                <Link key={article.id} href={`${URLS.ARTICLES}/${article.id}`}>
                  <div className="mb-5 rounded-xl transition hover:bg-zinc-800">
                    <time className="flex pt-5">
                      {/* <span className="ml-5 flex items-center border-l-2 border-zinc-500 pl-3.5 text-sm text-zinc-500">
                        {article.createdAt}
                      </span> */}
                    </time>
                    <h2 className="m-5 text-base font-semibold tracking-tight text-zinc-100">
                      {article.title}
                    </h2>
                    <p className=" m-5  mt-2 text-sm text-zinc-400">
                      {article.content.substring(0, 150) + "..."}
                    </p>
                    <h2 className="inherit ml-5 pb-5 text-sm font-medium text-teal-500">
                      Read Article {">"}{" "}
                    </h2>
                  </div>
                </Link>
              )
            )}
          </div>

          <div className="px-16 py-10">
            <div className="rounded-xl border border-zinc-700 px-4">
              <h2 className="m-5 text-base font-semibold tracking-tight text-zinc-100">
                {" "}
                <MailOutlineIcon className="text-zinc-500" />{" "}
                <span className="ml-4">Stay up to date</span>
              </h2>
              <p className="m-5  mt-2 text-sm text-zinc-400">
                Get notified when I publish something new, and unsubscribe at
                any time.
              </p>
              <input
                required
                className=" mx-4 mb-6 rounded-md border border-zinc-900/10  border-zinc-700 bg-zinc-800 px-4 py-1 pr-16  text-zinc-200 shadow-md shadow-zinc-800/5 placeholder:text-zinc-500 focus:border-teal-400 focus:outline-none focus:ring-teal-400/10"
                type="email"
                placeholder="Email Address"
              ></input>
              <button className="rounded-md bg-zinc-700 px-3 py-1 text-zinc-100 hover:bg-zinc-600 active:bg-zinc-700 active:text-zinc-100/70">
                Join
              </button>
            </div>
            <div className="mt-10 rounded-xl border border-zinc-700 px-4">
              <h2 className="m-5 text-base font-semibold tracking-tight text-zinc-100">
                {" "}
                <BusinessCenterIcon className="text-zinc-500" />{" "}
                <span className="ml-5">Work</span>
              </h2>
              <div className="flex-none">
                <h2 className="ml-5 flex text-left text-sm font-medium text-zinc-100">
                  <Image
                    src="/planetaria.svg"
                    width="30"
                    height="30"
                    alt="planetaria logo"
                    className="mt-1 rounded-full border border-zinc-700/50 bg-zinc-800 shadow-md shadow-zinc-800/5 ring-0 ring-zinc-900/5"
                  />
                  <span className="ml-5">Planetaria</span>
                </h2>
                <div className="ml-[4.25rem] flex justify-between pb-5">
                  <p className="text-xs text-zinc-400">CEO</p>
                  <p className="text-xs text-zinc-400"> 2019-present</p>
                </div>
              </div>
              <div className="flex-none">
                <h2 className="ml-5 flex text-left text-sm font-medium text-zinc-100">
                  <Image
                    src="/airbnb.svg"
                    width="30"
                    height="30"
                    alt="airbnb logo"
                    className="mt-1 rounded-full border border-zinc-700/50 bg-zinc-800 shadow-md shadow-zinc-800/5 ring-0 ring-zinc-900/5"
                  />
                  <span className="ml-5">Airbnb</span>
                </h2>
                <div className="ml-[4.25rem] flex justify-between pb-5">
                  <p className="text-xs text-zinc-400">Product Designer</p>
                  <p className="text-xs text-zinc-400 "> 2014-2019</p>
                </div>
              </div>

              <div className="flex-none">
                <h2 className="ml-5 flex text-left text-sm font-medium text-zinc-100">
                  <Image
                    src="/facebook.svg"
                    width="30"
                    height="30"
                    alt="facebook logo"
                    className="mt-1 rounded-full border border-zinc-700/50 bg-zinc-800 shadow-md shadow-zinc-800/5 ring-0 ring-zinc-900/5"
                  />
                  <span className="ml-5">Facebook</span>
                </h2>
                <div className="ml-[4.25rem] flex justify-between pb-5">
                  <p className="text-xs text-zinc-400">iOS SoftWare Engineer</p>
                  <p className="text-xs text-zinc-400"> 2011-2014</p>
                </div>
              </div>
              <div className="flex-none">
                <h2 className="ml-5 flex text-left text-sm font-medium text-zinc-100">
                  <Image
                    src="/starbucks.svg"
                    width="30"
                    height="30"
                    alt="starbucks logo"
                    className="mt-1 rounded-full border border-zinc-700/50 bg-zinc-800 shadow-md shadow-zinc-800/5 ring-0 ring-zinc-900/5"
                  />
                  <span className="ml-5">Starbucks</span>
                </h2>
                <div className="ml-[4.25rem] flex justify-between pb-5">
                  <p className="text-xs text-zinc-400">Shift Supervisor</p>
                  <p className="text-xs text-zinc-400"> 2008-2011</p>
                </div>
                <button className="mb-5 w-full rounded-md bg-zinc-800 px-3 py-1 text-zinc-200 hover:bg-zinc-700 active:bg-zinc-600 active:text-zinc-100/70">
                  {" "}
                  Download CV{" "}
                  <ArrowDownwardIcon style={{ fontSize: "medium" }} />{" "}
                </button>
              </div>
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
}
